{% set name = "aws-sam-translator" %}
{% set version = "1.79.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-sam-translator-{{ version }}.tar.gz
  sha256: 990f3043d00b6fd801b38ad780ecd058c315b7581b2e43fc013c9b6253f876e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - typing-extensions <5,>=4.4
    - python >=3.7,<4.0
    - boto3 >=1.19.5
    - jsonschema <5,>=3.2
    - pydantic >=1.8,<3

test:
  imports:
    - samtranslator
    - samtranslator.intrinsics
    - samtranslator.model
    - samtranslator.parser
    - samtranslator.plugins
    - samtranslator.policy_template_processor
    - samtranslator.public
    - samtranslator.sdk
    - samtranslator.swagger
    - samtranslator.translator
    - samtranslator.validator
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/awslabs/serverless-application-model
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: AWS Serverless Application Model (AWS SAM) prescribes rules for expressing Serverless applications on AWS.
  description: |
    You can use SAM to define serverless applications in simple and clean syntax. 
    This GitHub project is the starting point for AWS SAM. 
    It contains the SAM specification, the code that translates SAM templates into 
    AWS CloudFormation stacks, general information about the model, and examples of common applications.
  doc_url: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html
  dev_url: https://github.com/awslabs/serverless-application-model

extra:
  recipe-maintainers:
    - jan-janssen
    - mxr-conda
    - hajapy
    - rluria14
    - oblute
    - ndmaxar
